---

- hosts: webservers
  become: true
  tasks:

  vars:
    apache_package: "{{ 'httpd' if ansible_os_family == 'RedHat' else 'apache2' }}"
    php_package: "{{ 'php' if ansible_os_family == 'RedHat' else 'libapache2-mod-php'}}"
  
  tasks:

  - name: Install Apache and Php
    tags: apache,ubuntu,redhat
    ansible.builtin.package:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes

  - name: Enable Apache services
    tags: apache,redhat
    ansible.builtin.service:
      name: "{{ apache_package }}"
      state: started
      enabled: yes

  - name: change e-mail address for admin
    tags: apache,redhat
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin somebody@somewhere.net
    when: ansible_os_family == "RedHat"
    register: httpd

  - name: Restart httpd (RedHat)
    tags: apache,redhat
    service:
      name: httpd
      state: restarted
      update_cache: yes
    when: httpd.changed

  - name: Copy default html file
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
