---

#- hosts: all
#  become: true
#  tasks:

# - name: Install updates (CentOS)
#    dnf:
#      update_only: yes
#      update_cache: yes
#    when: ansible_os_family == "RedHat"

#  - name: Install updated (Ubuntu)
#    apt:
#      upgrade: dist
#      update_cache: yes
#    when: ansible_distribution == "Ubuntu"


- hosts: webservers
  become: true
  tasks:

  vars:
    apache_package: "{{ 'httpd' if ansible_os_family == 'RedHat' else 'apache2' }}"
    php_package: "{{ 'php' if ansible_os_family == 'RedHat' else 'libapache2-mod-php'}}"
  
  tasks:

  - name: Install Apache and Php
    tags: apache,centos,redhat
    ansible.builtin.package:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes

  - name: Enable Apache services
    tags: apache
    ansible.builtin.service:
      name: "{{ apache_package }}"
      state: started
      enabled: yes

  - name: Install Unzip
    tags: unzip
    package:
      name: unzip

  - name: Install Terraform
    tags: terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.14.4/terraform_1.14.4_linux_arm64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root

  - name: Copy default html file
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

